import { contextBridge, ipcRenderer } from "electron";
contextBridge.exposeInMainWorld("agentApi", {
    listTasks: () => ipcRenderer.invoke("tasks:list"),
    getTask: (id) => ipcRenderer.invoke("tasks:get", id),
    createTask: (input) => ipcRenderer.invoke("tasks:create", input),
    updateTask: (id, patch) => ipcRenderer.invoke("tasks:update", id, patch),
    deleteTask: (id) => ipcRenderer.invoke("tasks:delete", id),
    listRepositories: () => ipcRenderer.invoke("repos:list"),
    saveRepository: (profile) => ipcRenderer.invoke("repos:save", profile),
    deleteRepository: (id) => ipcRenderer.invoke("repos:delete", id),
    chooseRepositoryFolder: () => ipcRenderer.invoke("repos:choose-folder"),
    cloneRepository: (profile) => ipcRenderer.invoke("repos:clone", profile),
    attachRepository: (taskId, repositoryId) => ipcRenderer.invoke("tasks:attach-repo", taskId, repositoryId),
    detachRepository: (taskId, repositoryId) => ipcRenderer.invoke("tasks:detach-repo", taskId, repositoryId),
    getSetting: (key) => ipcRenderer.invoke("settings:get", key),
    setSetting: (key, value, secret) => ipcRenderer.invoke("settings:set", key, value, secret),
    startTask: (taskId) => ipcRenderer.invoke("tasks:start", taskId),
    sendTaskMessage: (taskId, message) => ipcRenderer.invoke("tasks:message", taskId, message),
    abortTask: () => ipcRenderer.invoke("tasks:abort"),
    runReview: (taskId) => ipcRenderer.invoke("tasks:review", taskId),
    resetReview: (taskId) => ipcRenderer.invoke("tasks:reset-review", taskId),
    resetDelivery: (taskId) => ipcRenderer.invoke("tasks:reset-delivery", taskId),
    submitMergeRequests: (taskId) => ipcRenderer.invoke("tasks:submit-mrs", taskId),
    refreshMergeStatus: () => ipcRenderer.invoke("tasks:refresh-merge-status"),
    manualComplete: (taskId) => ipcRenderer.invoke("tasks:manual-complete", taskId),
    importJiraTask: (keyOrUrl) => ipcRenderer.invoke("jira:import", keyOrUrl),
    syncJiraTasks: () => ipcRenderer.invoke("jira:sync"),
    testAtlassian: (kind) => ipcRenderer.invoke("atlassian:test", kind),
    respondTaskUi: (response) => ipcRenderer.invoke("task:ui-response", response),
    onTaskEvent: (callback) => { const listener = (_, event) => callback(event); ipcRenderer.on("task:event", listener); return () => ipcRenderer.removeListener("task:event", listener); }
});
//# sourceMappingURL=preload.js.map